# -*- coding: utf-8 -*-
"""customer-segmentation-with-rfm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw9VObpwQgVXEZy5wgGdPjBUdNfq54xp

# 1. Purpose of this notebook

To demonstrate the process of customer segmentation and its application in marketing strategies. Through concise analysis and actionable insights, it showcases how businesses can effectively categorize their customer base into distinct segments based on behavior and preferences.

By understanding the unique needs of each segment, businesses can tailor their marketing efforts to maximize customer engagement, loyalty, and revenue. Overall, this analysis serves as a practical guide for implementing customer segmentation to optimize marketing strategies and enhance overall business performance.

# 2. Import package and data
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('retail_sales_dataset.csv')

df.shape

"""# 3. Preprocessing"""

# standardize column names
df.columns = df.columns.str.lower().str.replace(' ','_')
df.head()

df['date'] = pd.to_datetime(df['date'])

print(df['gender'].value_counts(), '\n')
print(df['product_category'].value_counts())

print(df.customer_id.value_counts().max())

"""There are no repeat purchases. Each customer has only one transaction. To make our RFM customer segmentation practice fun and meaningful, let's introduce multiple purchases for each customer. We re-create the customer_id column and fill a random number between 1 to 1000."""

np.random.seed(101)

df['customer_id_new'] = np.random.randint(0, 500, size=1000)
df.head()

df.customer_id_new.value_counts()

"""Great. This better represents actual real-world data, which helps in our practice. Let's replace customer_id column with this new column."""

df['customer_id_new'] = df['customer_id_new'].apply(lambda x: f'CUST{str(x).zfill(3)}')

df['customer_id'] = df['customer_id_new']
df.head()

df = df.drop(columns=['customer_id_new'])
df.customer_id.value_counts().head()

"""# 4. RFM Customer Segmentation

RFM (Recency, Frequency, Monetary) customer segmentation is a marketing analysis tool that categorizes customers based on how recently they made a purchase, how often they purchase, and how much they spend. This method helps businesses identify their most valuable customers, understand buying patterns, and tailor marketing strategies to boost customer retention and maximize revenue. By focusing on the most profitable segments, RFM segmentation enhances personalized communication and marketing efficiency.
"""

max_date = df['date'].max()
max_date

# create customer-level dataset
customer_data = df.groupby('customer_id').agg({
    'date': lambda x: (max_date - x.max()).days,  # recency
    'transaction_id': 'count',  # frequency
    'total_amount': 'sum'  # monetary
})

customer_data.rename(columns={
    'date': 'recency',
    'transaction_id': 'frequency',
    'total_amount': 'monetary'
}, inplace=True)

customer_data.head()

# assign scores to each RFM component
quantiles = customer_data.quantile(q=[.25, .5, .75])
quantiles = quantiles.to_dict()

quantiles

def RScore(x, a, b):
    if x <= a:
        return 5
    elif a < x <= b:
        return 4
    elif b < x <= quantiles['monetary'][0.75]:
        return 3
    elif quantiles['monetary'][0.75] < x <= quantiles['frequency'][0.75]:
        return 2
    else:
        return 1

def FMScore(x, a, b): # frequency and monetary: higher better
    if x <= a:
        return 1
    elif a < x <= b:
        return 2
    elif b < x <= quantiles['frequency'][0.75]:
        return 3
    elif quantiles['frequency'][0.75] < x <= quantiles['monetary'][0.75]:
        return 4
    else:
        return 5

customer_data['R_Score'] = customer_data['recency'].apply(RScore, args=(quantiles['recency'][0.25], quantiles['recency'][0.5]))
customer_data['F_Score'] = customer_data['frequency'].apply(FMScore, args=(quantiles['frequency'][0.25], quantiles['frequency'][0.5]))
customer_data['M_Score'] = customer_data['monetary'].apply(RScore, args=(quantiles['monetary'][0.25], quantiles['monetary'][0.5]))

# calculate RFM score for each customer
customer_data['RFM_Score'] = customer_data['R_Score'].astype(str) + customer_data['F_Score'].astype(str) + customer_data['M_Score'].astype(str)
customer_data.head()

plt.figure(figsize=(10,4))
rfm_level_counts = customer_data['RFM_Score'].value_counts().sort_index()
sns.barplot(x=rfm_level_counts.index, y=rfm_level_counts.values)
plt.title('Distribution of RFM Scores')
plt.xlabel('RFM Score')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""### K Means Clustering"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(customer_data[['R_Score', 'F_Score', 'M_Score']])

inertia = []
K = range(1, 11)

for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(rfm_scaled)
    inertia.append(kmeans.inertia_)

# elbow curve to choose optimal clusters
plt.figure(figsize=(6, 4))
plt.plot(K, inertia, 'bo-')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.title('Elbow Method for Optimal k')
plt.show()

kmeans = KMeans(n_clusters=4, random_state=42)
customer_data['Cluster'] = kmeans.fit_predict(rfm_scaled)

cluster_summary = customer_data.groupby('Cluster').agg({
    'R_Score': 'mean',
    'F_Score': 'mean',
    'M_Score': 'mean'
}).reset_index()

cluster_summary

# Assigning the segment names
segment_names = {
    0: 'At Risk',
    1: 'Recent Customers',
    2: 'Big Spenders',
    3: 'Frequent Low Spenders'
}

# Assign the segment names to the Cluster
customer_data['Segment'] = customer_data['Cluster'].map(segment_names)

# Display the customer data with segments
customer_data[['R_Score', 'F_Score', 'M_Score', 'RFM_Score', 'Cluster', 'Segment']].head()

# size of each segment
segment_size = customer_data['Segment'].value_counts().reset_index()
segment_size.columns = ['Segment','Count']
segment_size

plt.figure(figsize=(7,3))
sns.countplot(data=customer_data, x='Segment', order=segment_size['Segment'])
plt.title('Customer Segments Distribution')
plt.xlabel('Segment')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45)
plt.show()

"""# 5. Recommendations

**Big Spenders (143 customers):**

Implement exclusive offers and VIP perks to capitalize on their high spending.
Provide personalized product recommendations to encourage further purchases.
Focus on exceptional customer service to reinforce loyalty and encourage repeat business.

**Recent Customers (114 customers):**

Nurture relationships with welcome emails and personalized recommendations.
Offer incentives like discounts or referral bonuses to encourage continued engagement.
Gather feedback through surveys to improve their experience and foster loyalty.

**At Risk (96 customers):**

Launch reactivation campaigns with personalized offers and promotions.
Address concerns and rebuild trust through targeted communication.
Collect feedback to identify pain points and improve satisfaction.

**Frequent Low Spenders (76 customers):**

Encourage larger purchases through upselling and cross-selling strategies.
Offer bundle deals or loyalty rewards to incentivize increased spending.
Build loyalty through personalized communication and tailored promotions.

Tailoring marketing strategies to each segment maximizes customer lifetime value and fosters long-term loyalty. Regular analysis ensures adaptability to evolving preferences, driving sustainable growth.
"""